const team = [
  {
    role: ["Supervisor", "Dean of Student Affairs"],
    name: "Prof. Mohamed Abo El-Azm",
    department: "Mechanical Engineering",
    linkedin: "",
    src: "/static/Team/Supervisor/Prof-Mohamed-Abo-Al-Azm.jpg",
  },
  {
    role: ["Mentor"],
    name: "Mohamed Ragab",
    department: "Communications Engineering",
    linkedin: "",
    src: "",
  },
  {
    role: ["Mentor"],
    name: "Omar Aman",
    department: "Mechatronics Engineering",
    linkedin: "",
    src: "",
  },
  {
    role: ["Mentor"],
    name: "Youssef Mehanna",
    department: "Computer Science",
    linkedin: "",
    src: "",
  },
  {
    role: ["Mentor"],
    name: "Ahmed Mohamed",
    department: "Communications Engineering",
    linkedin: "",
    src: "",
  },
  {
    role: ["Mentor"],
    name: "Aya Ashraf",
    department: "Communications Engineering",
    linkedin: "",
    src: "",
  },
  {
    role: ["Mentor"],
    name: "Osama Hesham",
    department: "Computer Engineering",
    linkedin: "",
    src: "",
  },
  {
    role: ["Mentor"],
    name: "Belal Abo Elkheir",
    department: "Computer Science",
    linkedin: "",
    src: "",
  },
  {
    role: ["Electrical Head", "CEO"],
    name: "Omar Ossama",
    department: "Electrical Engineering",
    linkedin: "",
    src: "",
  },
  {
    role: ["CTO"],
    name: "Fares Fathy",
    department: "Artificial Intelligence",
    linkedin: "",
    src: "",
  },
  {
    role: ["Mechanical Head"],
    name: "Abdelrahman Hikal",
    department: "Mechanical Engineering",
    linkedin: "",
    src: "",
  },
  {
    role: ["Software Head"],
    name: "Habiba Amr",
    department: "Computer Engineering",
    linkedin: "",
    src: "",
  },
  {
    role: ["Software Co-Head"],
    name: "Maya Hossam",
    department: "",
    linkedin: "",
    src: "",
  },
  { role: [""], name: "", department: "", linkedin: "", src: "" },
];

export default team;
